### ISSUE TITLE
对数据集规模有问题

### ISSUE THREAD

**Issue by dishegg** [ETVP/Multi-Modal-Co-learning#2]
您好，我把自己的数据集处理成267 x 256 x 256，会提示错误RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 32 but got size 33 for tensor number 1 in the list.但我把数据处理成311 x 256 x 256 在这一层就不会有问题，但在下一层也会有问题，想问一下是要把数据集处理成什么规模的？

**Comment by ZhongliangXue** [comment]
可以用 48x256x256, 96x256x256 等size

**Comment by dishegg** [comment]
它可以正常工作了 非常感谢您的回答！
